import { BellOutlined, CheckOutlined, DeleteOutlined, PlusOutlined } from '@ant-design/icons';
import { Alert as AntAlert, App, Button, Card, Col, Form, Input, InputNumber, Modal, Row, Select, Space, Switch, Table, Tabs, Tag, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../auth';
import { PageHeader } from '../components/PageHeader';
import { useI18n } from '../i18n';
import { operationsService } from '../service';
import type { AlertRule, ApplicationAlert, FailureFingerprint } from '../types';
import { formatTimestamp } from '../utils';

export function AlertsPage() {
  const { locale } = useI18n(); const en = locale === 'en-US'; const { session } = useAuth(); const { message } = App.useApp(); const [alerts, setAlerts] = useState<ApplicationAlert[]>([]); const [rules, setRules] = useState<AlertRule[]>([]); const [fingerprints, setFingerprints] = useState<FailureFingerprint[]>([]); const [editing, setEditing] = useState<Partial<AlertRule>>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [a, r, f] = await Promise.all([operationsService.listAlerts(), operationsService.listAlertRules(), operationsService.listFingerprints()]); setAlerts(a); setRules(r); setFingerprints(f); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [load]);
  const save = async () => { if (!editing) return; try { await operationsService.saveAlertRule(editing); setEditing(undefined); message.success(en ? 'Rule saved' : '规则已保存'); void load(); } catch (e) { message.error(e instanceof Error ? e.message : String(e)); } };
  const alertColumns = [
    { title: en ? 'Severity' : '级别', dataIndex: 'severity', width: 90, render: (v: string) => <Tag color={v === 'error' ? 'red' : v === 'warning' ? 'orange' : 'blue'}>{v}</Tag> },
    { title: en ? 'Alert' : '告警', render: (_: unknown, row: ApplicationAlert) => <div><Typography.Text strong>{row.summary}</Typography.Text><br/><Typography.Text type="secondary">{row.ruleName} · {row.fingerprint}</Typography.Text></div> },
    { title: en ? 'Application' : '作业', render: (_: unknown, row: ApplicationAlert) => `${row.namespace}/${row.applicationName}` },
    { title: en ? 'Status' : '状态', dataIndex: 'status', render: (v: string) => <Tag>{v}</Tag> }, { title: en ? 'Last seen' : '最后发现', dataIndex: 'lastSeenAt', render: (value: string) => formatTimestamp(value) },
    { title: en ? 'Actions' : '操作', width: 190, render: (_: unknown, row: ApplicationAlert) => session?.role === 'admin' && row.status !== 'recovered' ? <Space><Button size="small" icon={<CheckOutlined />} onClick={async () => { await operationsService.updateAlert(row.id, 'acknowledged'); void load(); }}>{en ? 'Acknowledge' : '确认'}</Button><Button size="small" onClick={async () => { await operationsService.updateAlert(row.id, 'silenced', new Date(Date.now() + 3600000).toISOString()); void load(); }}>{en ? 'Silence 1h' : '静默 1 小时'}</Button></Space> : null },
  ];
  return <><PageHeader title={en ? 'Alert center' : '告警中心'} subtitle={en ? 'Actionable alerts, lifecycle state, and aggregated failure fingerprints.' : '集中查看可操作告警、生命周期状态和聚合故障指纹。'} extra={session?.role === 'admin' && <Button type="primary" icon={<PlusOutlined />} onClick={() => setEditing({ enabled: true, severity: 'warning', type: 'failure', namespaces: [], notifyWebhook: false })}>{en ? 'New rule' : '新建规则'}</Button>} />
    {error && <AntAlert type="error" showIcon message={error} action={<Button onClick={load}>{en ? 'Retry' : '重试'}</Button>} />}
    <Tabs items={[
      { key: 'alerts', label: <Space><BellOutlined />{en ? 'Alerts' : '告警'}<Tag>{alerts.filter((x) => x.status === 'active').length}</Tag></Space>, children: <Card className="table-card"><Table rowKey="id" loading={loading} dataSource={alerts} columns={alertColumns} expandable={{ expandedRowRender: (row) => <div><Typography.Title level={5}>{en ? 'Evidence' : '证据'}</Typography.Title>{row.evidence.map((x) => <div key={x}>• {x}</div>)}<Typography.Title level={5}>{en ? 'Recommendation' : '建议操作'}</Typography.Title><Typography.Text>{row.recommendation || '—'} ({row.confidence})</Typography.Text></div> }} /></Card> },
      { key: 'rules', label: en ? 'Rules' : '规则', children: <Card className="table-card"><Table rowKey="id" loading={loading} dataSource={rules} columns={[{ title: en ? 'Rule' : '规则', dataIndex: 'name' },{ title: en ? 'Type' : '类型', dataIndex: 'type' },{ title: en ? 'Namespaces' : '命名空间', render: (_: unknown, r: AlertRule) => r.namespaces.length ? r.namespaces.join(', ') : (en ? 'All permitted' : '所有授权空间') },{ title: en ? 'Enabled' : '启用', dataIndex: 'enabled', render: (v: boolean) => <Switch checked={v} disabled /> },{ title: en ? 'Actions' : '操作', render: (_: unknown, r: AlertRule) => session?.role === 'admin' && <Space><Button size="small" onClick={() => setEditing(r)}>{en ? 'Edit' : '编辑'}</Button><Button size="small" danger type="text" icon={<DeleteOutlined />} onClick={async () => { await operationsService.deleteAlertRule(r.id); void load(); }} /></Space> }]} /></Card> },
      { key: 'fingerprints', label: en ? 'Failure fingerprints' : '故障指纹', children: <Row gutter={[16,16]}>{fingerprints.map((x) => <Col xs={24} lg={12} key={x.fingerprint}><Card><Space><Tag color={x.severity === 'error' ? 'red' : 'orange'}>{x.code}</Tag><Typography.Text strong>{x.count}×</Typography.Text></Space><Typography.Paragraph>{x.namespace}/{x.sampleApplication}</Typography.Paragraph><Typography.Paragraph type="secondary">{x.recommendation}</Typography.Paragraph></Card></Col>)}</Row> },
    ]} />
    <Modal open={Boolean(editing)} title={en ? 'Alert rule' : '告警规则'} onCancel={() => setEditing(undefined)} onOk={save}><Form layout="vertical"><Form.Item label={en ? 'Name' : '名称'} required><Input value={editing?.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></Form.Item><Form.Item label={en ? 'Rule type' : '规则类型'}><Select value={editing?.type} onChange={(type) => setEditing({ ...editing, type })} options={[['failure', en ? 'Application failure' : '作业失败'],['pending', en ? 'Long pending' : '长时间 Pending'],['resource', en ? 'Resource pressure' : '资源异常'],['retries', en ? 'Repeated retries' : '重复重试']].map(([value,label]) => ({ value,label }))} /></Form.Item><Form.Item label={en ? 'Namespaces' : '命名空间'}><Select mode="multiple" value={editing?.namespaces} onChange={(namespaces) => setEditing({ ...editing, namespaces })} options={(session?.namespaces || []).map((x) => ({ value: x, label: x }))} /></Form.Item><Row gutter={12}><Col span={8}><Form.Item label={en ? 'Pending minutes' : 'Pending 分钟'}><InputNumber min={1} value={editing?.thresholdMinutes} onChange={(thresholdMinutes) => setEditing({ ...editing, thresholdMinutes: thresholdMinutes || undefined })} /></Form.Item></Col><Col span={8}><Form.Item label={en ? 'Usage ratio' : '使用率阈值'}><InputNumber min={0.1} max={2} step={0.05} value={editing?.thresholdValue} onChange={(thresholdValue) => setEditing({ ...editing, thresholdValue: thresholdValue || undefined })} /></Form.Item></Col><Col span={8}><Form.Item label={en ? 'Retry count' : '重试次数'}><InputNumber min={1} value={editing?.minimumRetries} onChange={(minimumRetries) => setEditing({ ...editing, minimumRetries: minimumRetries || undefined })} /></Form.Item></Col></Row><Form.Item label={en ? 'Severity' : '级别'}><Select value={editing?.severity} onChange={(severity) => setEditing({ ...editing, severity })} options={['info','warning','error'].map((x) => ({ value: x, label: x }))} /></Form.Item><Space><Switch checked={editing?.enabled} onChange={(enabled) => setEditing({ ...editing, enabled })} />{en ? 'Enabled' : '启用'}<Switch checked={editing?.notifyWebhook} onChange={(notifyWebhook) => setEditing({ ...editing, notifyWebhook })} />Webhook</Space></Form></Modal>
  </>;
}
