import { DeleteOutlined, EyeOutlined, ReloadOutlined, SearchOutlined, StarFilled, StarOutlined, StopOutlined } from '@ant-design/icons';
import { Alert, App, Button, Card, Input, Modal, Progress, Select, Space, Table, Tag, Tooltip, Typography } from 'antd';
import type { ColumnsType, TableProps } from 'antd/es/table';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
import { ApplicationOperationModal } from '../components/KillModal';
import { PageHeader } from '../components/PageHeader';
import { StatusTag } from '../components/StatusTag';
import { useI18n } from '../i18n';
import { operationsService } from '../service';
import { runtimeConfig } from '../runtimeConfig';
import type { ApplicationState, BatchActionItem, SparkApplication } from '../types';
import { canDelete, canKill, formatCpu, formatDuration, formatMemory, formatTimestamp, isKillableState, isTerminalState, sumResources } from '../utils';
import { useApplicationEvents } from '../useApplicationEvents';

export function ApplicationsPage() {
  const { t, locale } = useI18n(); const en = locale === 'en-US'; const { session } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const { message } = App.useApp();
  const query = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const [apps, setApps] = useState<SparkApplication[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [keyword, setKeyword] = useState(query.get('keyword') || ''); const [state, setState] = useState<ApplicationState | undefined>((query.get('state') as ApplicationState) || undefined); const [namespace, setNamespace] = useState(query.get('namespace') || undefined); const [favorite, setFavoriteFilter] = useState(query.get('favorite') === 'true');
  const [page, setPage] = useState(Number(query.get('page') || 1)); const [pageSize, setPageSize] = useState(Number(query.get('pageSize') || 20)); const [sort, setSort] = useState(query.get('sort') || 'createdAt'); const [direction, setDirection] = useState<'asc' | 'desc'>((query.get('direction') as 'asc' | 'desc') || 'desc');
  const [favorites, setFavorites] = useState<Set<string>>(new Set()); const [selected, setSelected] = useState<SparkApplication[]>([]); const [target, setTarget] = useState<{ application: SparkApplication; operation: 'kill' | 'delete' }>(); const [batch, setBatch] = useState<{ operation: 'kill' | 'delete'; preview: BatchActionItem[]; reason: string; executing?: boolean }>();
  const filters = useMemo(() => ({ keyword: keyword.trim() || undefined, state, namespace, favorite: favorite || undefined, page, pageSize, sort: sort as 'createdAt', direction }), [keyword, state, namespace, favorite, page, pageSize, sort, direction]);
  const syncURL = useCallback(() => { const next = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== '' && !(key === 'page' && value === 1)) next.set(key, String(value)); }); navigate({ search: next.toString() }, { replace: true }); }, [filters, navigate]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [result, starred] = await Promise.all([operationsService.listApplications(filters), operationsService.listFavorites()]); setApps(result.items); setTotal(result.total); setFavorites(new Set(starred.map((x) => `${x.namespace}/${x.application}`))); } catch (e) { setError(e instanceof Error ? e.message : 'Failed to load'); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = window.setTimeout(() => { syncURL(); void load(); }, 180); return () => window.clearTimeout(timer); }, [load, syncURL]);
  useEffect(() => { const timer = window.setInterval(() => void load(), runtimeConfig.dashboard.refreshIntervalSeconds * 1000); return () => window.clearInterval(timer); }, [load]); useApplicationEvents(() => { void load(); });
  const toggleFavorite = async (row: SparkApplication) => { const key = `${row.namespace}/${row.name}`; await operationsService.setFavorite(row.namespace, row.name, !favorites.has(key)); void load(); };
  const openBatch = async (operation: 'kill' | 'delete') => { try { const preview = await operationsService.batchPreview(operation, selected.map(({ namespace: ns, name }) => ({ namespace: ns, name }))); setBatch({ operation, preview, reason: '' }); } catch (e) { message.error(e instanceof Error ? e.message : String(e)); } };
  const executeBatch = async () => { if (!batch) return; setBatch({ ...batch, executing: true }); try { const result = await operationsService.batchExecute(batch.operation, batch.preview.map(({ namespace: ns, name }) => ({ namespace: ns, name })), batch.reason); const failed = result.items.filter((x) => x.result === 'FAILED').length; message.success(en ? `${result.items.length - failed} succeeded, ${failed} failed` : `${result.items.length - failed} 项成功，${failed} 项失败`); setBatch(undefined); setSelected([]); void load(); } catch (e) { message.error(e instanceof Error ? e.message : String(e)); setBatch({ ...batch, executing: false }); } };
  const columns: ColumnsType<SparkApplication> = [
    { title: '', width: 44, fixed: 'left', render: (_, row) => <Button type="text" aria-label="favorite" icon={favorites.has(`${row.namespace}/${row.name}`) ? <StarFilled style={{ color: '#f5b301' }} /> : <StarOutlined />} onClick={() => void toggleFavorite(row)} /> },
    { title: t('application'), dataIndex: 'name', width: 230, sorter: true, render: (value, row) => <div className="app-cell"><span className="spark-mini-mark">S</span><span><Typography.Link onClick={() => navigate(`/applications/${row.namespace}/${row.name}`)}>{value}</Typography.Link><small>{row.namespace}</small></span></div> },
    { title: t('owner'), dataIndex: 'owner', width: 105, sorter: true }, { title: t('status'), dataIndex: 'state', width: 150, sorter: true, render: (value) => <StatusTag state={value} /> }, { title: t('duration'), width: 100, render: (_, row) => formatDuration(row) },
    { title: t('createdAt'), dataIndex: 'createdAt', width: 165, sorter: true, render: (value) => formatTimestamp(value) }, { title: t('finishedAt'), dataIndex: 'finishedAt', width: 165, sorter: true, render: (value) => value ? formatTimestamp(value) : '—' },
    { title: t('driver'), width: 125, render: (_, row) => <div className="resource-cell"><b>{formatCpu(row.driver.request.cpu)}</b><small>{formatMemory(row.driver.request.memoryGiB)}</small></div> }, { title: t('executors'), width: 105, align: 'center', render: (_, row) => <b>{row.executors.length}</b> },
    { title: `${t('cpu')} · used/request`, width: 190, render: (_, row) => { const value = sumResources(row); const percent = value.requested.cpu ? Math.min(100, Math.round(value.used.cpu / value.requested.cpu * 100)) : 0; return <div className="table-progress"><span>{formatCpu(value.used.cpu)} / {formatCpu(value.requested.cpu)}</span><Progress size="small" percent={percent} showInfo={false} /></div>; } },
    { title: `${t('memory')} · used/request`, width: 205, render: (_, row) => { const value = sumResources(row); const percent = value.requested.memoryGiB ? Math.min(100, Math.round(value.used.memoryGiB / value.requested.memoryGiB * 100)) : 0; return <div className="table-progress"><span>{formatMemory(value.used.memoryGiB)} / {formatMemory(value.requested.memoryGiB)}</span><Progress size="small" percent={percent} showInfo={false} strokeColor="#7a58e8" /></div>; } },
    { title: t('action'), key: 'action', width: 130, fixed: 'right', render: (_, row) => <Space><Tooltip title={t('details')}><Button size="small" type="text" icon={<EyeOutlined />} onClick={() => navigate(`/applications/${row.namespace}/${row.name}`)} /></Tooltip>{runtimeConfig.features.kill && isKillableState(row.state) && <Button aria-label="kill" size="small" danger type="text" disabled={!canKill(session?.role ?? 'viewer')} icon={<StopOutlined />} onClick={() => setTarget({ application: row, operation: 'kill' })} />}{runtimeConfig.features.kill && isTerminalState(row.state) && <Button aria-label="delete" size="small" danger type="text" disabled={!canDelete(session?.role ?? 'viewer')} icon={<DeleteOutlined />} onClick={() => setTarget({ application: row, operation: 'delete' })} />}</Space> },
  ];
  const onChange: TableProps<SparkApplication>['onChange'] = (pagination, _tableFilters, sorter) => { setPage(pagination.current || 1); setPageSize(pagination.pageSize || 20); const value = Array.isArray(sorter) ? sorter[0] : sorter; if (value?.field) { setSort(String(value.field)); setDirection(value.order === 'ascend' ? 'asc' : 'desc'); } };
  return <><PageHeader title={t('applications')} subtitle={en ? `${total} matching applications` : `${total} 个匹配作业`} extra={<Button icon={<ReloadOutlined />} onClick={load}>{t('refresh')}</Button>} />
    <Card className="filter-card"><div className="filter-bar"><Input allowClear value={keyword} onChange={(e) => { setKeyword(e.target.value); setPage(1); }} prefix={<SearchOutlined />} placeholder={t('search')} className="search-input" /><Select allowClear value={state} onChange={(v) => { setState(v); setPage(1); }} placeholder={t('status')} options={['RUNNING','COMPLETED','FAILED','SUBMISSION_FAILED','PENDING','SUBMITTED','FAILING','UNKNOWN','KILLED'].map((value) => ({ value, label: value }))} /><Select allowClear value={namespace} onChange={(v) => { setNamespace(v); setPage(1); }} placeholder={t('namespace')} options={(session?.namespaces || runtimeConfig.cluster.namespaces).map((value) => ({ value, label: value }))} /><Button type={favorite ? 'primary' : 'default'} icon={<StarOutlined />} onClick={() => { setFavoriteFilter(!favorite); setPage(1); }}>{en ? 'Favorites' : '收藏'}</Button><Button onClick={() => { setKeyword(''); setState(undefined); setNamespace(undefined); setFavoriteFilter(false); setPage(1); setSort('createdAt'); setDirection('desc'); }}>{t('resetFilters')}</Button></div></Card>
    {session?.role === 'admin' && selected.length > 0 && <Card size="small"><Space wrap><Tag color="blue">{en ? `${selected.length} selected` : `已选择 ${selected.length} 项`}</Tag><Button danger icon={<StopOutlined />} onClick={() => void openBatch('kill')}>{en ? 'Batch terminate' : '批量终止'}</Button><Button danger icon={<DeleteOutlined />} onClick={() => void openBatch('delete')}>{en ? 'Batch delete' : '批量删除'}</Button></Space></Card>}
    {error ? <Alert type="error" showIcon message={error} action={<Button onClick={load}>{t('retry')}</Button>} /> : <Card className="table-card"><Table rowKey="id" loading={loading} dataSource={apps} columns={columns} onChange={onChange} rowSelection={session?.role === 'admin' ? { selectedRowKeys: selected.map((x) => x.id), onChange: (_keys, rows) => setSelected(rows) } : undefined} scroll={{ x: 1820 }} pagination={{ current: page, pageSize, total, showSizeChanger: true, showTotal: (value) => `${value} applications` }} /></Card>}
    {target && <ApplicationOperationModal application={target.application} operation={target.operation} open onClose={() => setTarget(undefined)} onCompleted={() => void load()} />}
    <Modal open={Boolean(batch)} title={batch?.operation === 'kill' ? (en ? 'Confirm batch termination' : '确认批量终止') : (en ? 'Confirm batch deletion' : '确认批量删除')} okButtonProps={{ danger: true, loading: batch?.executing, disabled: !batch?.preview.some((x) => x.allowed) }} onCancel={() => setBatch(undefined)} onOk={executeBatch}><Typography.Paragraph type="secondary">{en ? 'Every item is re-authorized and audited independently by the backend.' : '后端会逐项重新进行权限检查，并分别写入审计记录。'}</Typography.Paragraph>{batch?.preview.map((x) => <div key={`${x.namespace}/${x.name}`}><Tag color={x.allowed ? 'success' : 'error'}>{x.allowed ? 'READY' : 'BLOCKED'}</Tag>{x.namespace}/{x.name}{x.reason && <Typography.Text type="secondary"> — {x.reason}</Typography.Text>}</div>)}<Input.TextArea style={{ marginTop: 16 }} value={batch?.reason} onChange={(e) => batch && setBatch({ ...batch, reason: e.target.value })} placeholder={en ? 'Operation reason (optional)' : '操作原因（可选）'} /></Modal>
  </>;
}
