import { CopyOutlined, DeleteOutlined, EditOutlined, FileAddOutlined, PlayCircleOutlined } from '@ant-design/icons';
import { Alert, App, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Switch, Table, Tag, Typography } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth';
import { PageHeader } from '../components/PageHeader';
import { useI18n } from '../i18n';
import { operationsService } from '../service';
import type { ApplicationTemplate, TemplateParameter } from '../types';
import { formatTimestamp } from '../utils';

type TemplateForm = Partial<ApplicationTemplate> & { parametersText?: string };

export function TemplatesPage() {
  const { locale } = useI18n(); const en = locale === 'en-US'; const { session } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const { message } = App.useApp();
  const [items, setItems] = useState<ApplicationTemplate[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<TemplateForm>(); const [rendering, setRendering] = useState<ApplicationTemplate>(); const [values, setValues] = useState<Record<string, string>>({});
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await operationsService.listTemplates(session?.role === 'admin')); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, [session?.role]);
  useEffect(() => { void load(); const state = location.state as { manifest?: string; namespace?: string } | null; if (state?.manifest && session?.role === 'admin') setEditing({ name: '', namespace: state.namespace, manifest: state.manifest, parameters: [], disabled: false }); }, [load, location.state, session?.role]);
  const save = async () => { if (!editing) return; try { const parameters = JSON.parse(editing.parametersText || JSON.stringify(editing.parameters || [])) as TemplateParameter[]; await operationsService.saveTemplate({ ...editing, parameters }); message.success(en ? 'Template saved' : '模板已保存'); setEditing(undefined); void load(); } catch (e) { message.error(e instanceof Error ? e.message : String(e)); } };
  const render = async () => { if (!rendering) return; try { const result = await operationsService.renderTemplate(rendering.id, values); navigate('/submit', { state: { manifest: result.serverYaml, namespace: rendering.namespace, source: rendering.name } }); } catch (e) { message.error(e instanceof Error ? e.message : String(e)); } };
  return <>
    <PageHeader title={en ? 'Application templates' : '作业模板'} subtitle={en ? 'Versioned, parameterized SparkApplication manifests without embedded secrets.' : '支持版本记录和参数校验的 SparkApplication 清单，不保存 Secret 明文。'} extra={session?.role === 'admin' && <Button type="primary" icon={<FileAddOutlined />} onClick={() => setEditing({ namespace: session.namespaces?.[0] || '', manifest: '', parameters: [], disabled: false })}>{en ? 'New template' : '新建模板'}</Button>} />
    {error && <Alert type="error" showIcon message={error} action={<Button onClick={load}>{en ? 'Retry' : '重试'}</Button>} />}
    <Card className="table-card"><Table rowKey="id" loading={loading} dataSource={items} scroll={{ x: 1050 }} columns={[
      { title: en ? 'Template' : '模板', dataIndex: 'name', render: (name, row) => <Space><Typography.Text strong>{name}</Typography.Text>{row.disabled && <Tag>{en ? 'Disabled' : '已禁用'}</Tag>}</Space> },
      { title: en ? 'Namespace' : '命名空间', dataIndex: 'namespace' }, { title: en ? 'Version' : '版本', dataIndex: 'version', render: (v) => <Tag color="blue">v{v}</Tag> },
      { title: en ? 'Parameters' : '参数', render: (_, row) => row.parameters.length }, { title: en ? 'Updated' : '更新时间', dataIndex: 'updatedAt', render: (value) => formatTimestamp(value) },
      { title: en ? 'Actions' : '操作', fixed: 'right', width: 220, render: (_, row) => <Space><Button size="small" icon={<PlayCircleOutlined />} disabled={row.disabled || session?.role !== 'admin'} onClick={() => { setRendering(row); setValues(Object.fromEntries(row.parameters.map((p) => [p.name, p.default || '']))); }}>{en ? 'Use' : '使用'}</Button>{session?.role === 'admin' && <><Button size="small" type="text" icon={<EditOutlined />} onClick={async () => { const full = await operationsService.getTemplate(row.id); setEditing({ ...full, parametersText: JSON.stringify(full.parameters, null, 2) }); }} /><Button size="small" type="text" icon={<CopyOutlined />} onClick={async () => { await operationsService.copyTemplate(row.id, `${row.name} copy`); void load(); }} /><Button size="small" danger type="text" icon={<DeleteOutlined />} onClick={() => Modal.confirm({ title: en ? 'Delete this template?' : '删除此模板？', onOk: async () => { await operationsService.deleteTemplate(row.id); void load(); } })} /></>}</Space> },
    ]} /></Card>
    <Modal open={Boolean(editing)} title={editing?.id ? (en ? 'Edit template' : '编辑模板') : (en ? 'New template' : '新建模板')} width="min(1050px, 94vw)" onCancel={() => setEditing(undefined)} onOk={save} okText={en ? 'Save' : '保存'}>
      {editing && <Form layout="vertical"><Space wrap style={{ width: '100%' }}><Form.Item label={en ? 'Name' : '名称'} required><Input value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></Form.Item><Form.Item label={en ? 'Namespace' : '命名空间'} required><Select style={{ width: 220 }} value={editing.namespace} options={(session?.namespaces || []).map((x) => ({ value: x, label: x }))} onChange={(namespace) => setEditing({ ...editing, namespace })} /></Form.Item><Form.Item label={en ? 'Disabled' : '禁用'}><Switch checked={editing.disabled} onChange={(disabled) => setEditing({ ...editing, disabled })} /></Form.Item></Space><Form.Item label={en ? 'Description' : '描述'}><Input value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} /></Form.Item><Form.Item label={en ? 'Manifest with {{parameter}} placeholders' : '带 {{参数}} 占位符的清单'} required><Input.TextArea className="yaml-editor" autoSize={{ minRows: 16, maxRows: 26 }} value={editing.manifest} onChange={(e) => setEditing({ ...editing, manifest: e.target.value })} /></Form.Item><Form.Item label={en ? 'Parameter definitions (JSON)' : '参数定义（JSON）'} extra={en ? 'Fields: name, type, required, default, enum, pattern. Secret-like parameter names are rejected.' : '字段：name、type、required、default、enum、pattern。类似 Secret 的参数名会被拒绝。'}><Input.TextArea autoSize={{ minRows: 5, maxRows: 12 }} value={editing.parametersText ?? JSON.stringify(editing.parameters || [], null, 2)} onChange={(e) => setEditing({ ...editing, parametersText: e.target.value })} /></Form.Item></Form>}
    </Modal>
    <Modal open={Boolean(rendering)} title={en ? `Use ${rendering?.name}` : `使用 ${rendering?.name}`} onCancel={() => setRendering(undefined)} onOk={render} okText={en ? 'Render and validate' : '渲染并校验'}>{rendering?.parameters.map((p) => <div key={p.name} style={{ marginBottom: 14 }}><Typography.Text strong>{p.name}{p.required ? ' *' : ''}</Typography.Text><Typography.Paragraph type="secondary">{p.description}</Typography.Paragraph>{p.enum?.length ? <Select style={{ width: '100%' }} value={values[p.name]} options={p.enum.map((x) => ({ value: x, label: x }))} onChange={(v) => setValues({ ...values, [p.name]: v })} /> : p.type === 'number' || p.type === 'integer' ? <InputNumber style={{ width: '100%' }} value={Number(values[p.name] || 0)} onChange={(v) => setValues({ ...values, [p.name]: String(v ?? '') })} /> : <Input value={values[p.name]} onChange={(e) => setValues({ ...values, [p.name]: e.target.value })} />}</div>)}</Modal>
  </>;
}
